[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "infinimetrics"
version = "0.1.0"
description = "An InfiniTensor-featured comprehensive accelerator evaluation framework"
dependencies = [
    
]

[tool.setuptools.packages.find]
where = ["src"]
